### ISSUE TITLE
Cleanup done automatically for Jest/Mocha/Jasmine (according to docs)

### ISSUE THREAD

**Issue by jamiecoe** [oliverjam/learn-react-testing#12]
Apparently `cleanup()` is done automatically if the testing framework you're using supports the `afterEach` global (like mocha, Jest, and Jasmine):

https://testing-library.com/docs/react-testing-library/api#cleanup

Would this make the following section of the README unnecessary?
```
Note:

If you read the docs for render you'll see that it's recommended to be used with the cleanup function. This will ensure you don't end up with lots of copies of your component in the same document.

You can use Jest's handy method that runs after each test to do this: afterEach(cleanup).
```

**Comment by oliverjam** [comment]
Huh [that's new](https://github.com/testing-library/react-testing-library/pull/430), sweet. Thanks for finding that! Want to do a PR to remove that section?

**Comment by jamiecoe** [comment]
No probs! Will make PR 👍

**Comment by oliverjam** [comment]
Thank you 🙏
