### ISSUE TITLE
fetch-mock links needs updating

### ISSUE THREAD

**Issue by helenzhou6** [oliverjam/learn-react-testing#4]
On Readme - correct link is now: http://www.wheresrhys.co.uk/fetch-mock/#aboutquickstart

**Comment by oliverjam** [comment]
Thanks. I was thinking about dropping this entirely since we could just mock it ourselves with `jest.fn`

**Comment by oliverjam** [comment]
Forgot to relate the commits but this is done. Dependency gone and native mocking in place
